### ISSUE TITLE
Missing message field for failed specs with stack traces

### ISSUE THREAD

**Issue by georgeelboustani** [onury/jasmine-console-reporter#7]
When a spec fails with a stack trace, the logged error info does not contain the message field.

This is what it currently outputs:
```
1) unit/email/mailhub sendEmail() : logs no errors with a valid request
       at <Jasmine>
       at UserContext.fit /Users/gelboustani/src/domain-claim-service/test/unit/email/mailhub-client.spec.js:150:70
       at <Jasmine>
       at runCallback timers.js:757:18
       at tryOnImmediate timers.js:718:5
       at processImmediate [as _immediateCallback] timers.js:698:5
       at <Jasmine>
       at UserContext.afterEach /Users/gelboustani/src/domain-claim-service/test/unit/email/mailhub-client.spec.js:79:24
       at <Jasmine>
       at runCallback timers.js:757:18
       at tryOnImmediate timers.js:718:5
       at processImmediate [as _immediateCallback] timers.js:698:5
```

Ideally, it would've printed:
```
1) unit/email/mailhub sendEmail() : logs no errors with a valid request
   ReferenceError: user is not defined
       at <Jasmine>
       at UserContext.fit /Users/gelboustani/src/domain-claim-service/test/unit/email/mailhub-client.spec.js:150:70
       at <Jasmine>
       at runCallback timers.js:757:18
       at tryOnImmediate timers.js:718:5
       at processImmediate [as _immediateCallback] timers.js:698:5
   TypeError: Cannot read property 'calls' of undefined
       at <Jasmine>
       at UserContext.afterEach /Users/gelboustani/src/domain-claim-service/test/unit/email/mailhub-client.spec.js:79:24
       at <Jasmine>
       at runCallback timers.js:757:18
       at tryOnImmediate timers.js:718:5
       at processImmediate [as _immediateCallback] timers.js:698:5
```

A potential fix is to concatenate the message field to the error message where the failure expectation with stack trace is handled. i.e. in ```index.js:224```

Replace ```errInfo = utils.reStack(failedExpectation.stack, options.cleanStack, style);```
with ```errInfo = utils.reStack(failedExpectation.message + '\n' + failedExpectation.stack, options.cleanStack, style);```

**Comment by onury** [comment]
I cannot reproduce this. It always logs the message within the stack.
- Can you provide an example to reproduce this?
- What is your JCR configuration? (especially `cleanStack` value)
- Which version of the module are you using?
- OS/version?
- Node/version?
